# Generated by Django 3.2.19 on 2023-06-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_history', '0003_alter_fieldhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldhistory',
            name='table_name',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
