# Generated by Django 3.2.19 on 2023-06-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_history', '0004_alter_fieldhistory_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldhistory',
            name='user',
        ),
    ]
