# Generated by Django 3.2.19 on 2023-06-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_history', '0005_remove_fieldhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldhistory',
            name='user',
            field=models.CharField(default=None, max_length=50, null=True, blank=True),
            preserve_default=False,
        ),
    ]
